name: "Garnet Labs"
description: "Check vulnerabilities inside the dependencies"
inputs:
  repo-token:
    description: "GITHUB_TOKEN secret"
    required: true
runs:
  using: "node12"
  main: "index.js"
